# Generated by Django 3.1.2 on 2020-10-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('maiden_name', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_step_child', models.BooleanField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, null=True, related_name='cs', to='family.FamilyMember')),
                ('parents', models.ManyToManyField(blank=True, null=True, related_name='ps', to='family.FamilyMember')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('is_divorced', models.BooleanField()),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descendant', to='family.familymember')),
                ('in_law', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_law', to='family.familymember')),
            ],
        ),
    ]
